/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Medicine } from "./Medicine";
import { MedicineCountArgs } from "./MedicineCountArgs";
import { MedicineFindManyArgs } from "./MedicineFindManyArgs";
import { MedicineFindUniqueArgs } from "./MedicineFindUniqueArgs";
import { CreateMedicineArgs } from "./CreateMedicineArgs";
import { UpdateMedicineArgs } from "./UpdateMedicineArgs";
import { DeleteMedicineArgs } from "./DeleteMedicineArgs";
import { MedicineService } from "../medicine.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Medicine)
export class MedicineResolverBase {
  constructor(
    protected readonly service: MedicineService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Medicine",
    action: "read",
    possession: "any",
  })
  async _medicinesMeta(
    @graphql.Args() args: MedicineCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Medicine])
  @nestAccessControl.UseRoles({
    resource: "Medicine",
    action: "read",
    possession: "any",
  })
  async medicines(
    @graphql.Args() args: MedicineFindManyArgs
  ): Promise<Medicine[]> {
    return this.service.medicines(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Medicine, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Medicine",
    action: "read",
    possession: "own",
  })
  async medicine(
    @graphql.Args() args: MedicineFindUniqueArgs
  ): Promise<Medicine | null> {
    const result = await this.service.medicine(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Medicine)
  @nestAccessControl.UseRoles({
    resource: "Medicine",
    action: "create",
    possession: "any",
  })
  async createMedicine(
    @graphql.Args() args: CreateMedicineArgs
  ): Promise<Medicine> {
    return await this.service.createMedicine({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Medicine)
  @nestAccessControl.UseRoles({
    resource: "Medicine",
    action: "update",
    possession: "any",
  })
  async updateMedicine(
    @graphql.Args() args: UpdateMedicineArgs
  ): Promise<Medicine | null> {
    try {
      return await this.service.updateMedicine({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Medicine)
  @nestAccessControl.UseRoles({
    resource: "Medicine",
    action: "delete",
    possession: "any",
  })
  async deleteMedicine(
    @graphql.Args() args: DeleteMedicineArgs
  ): Promise<Medicine | null> {
    try {
      return await this.service.deleteMedicine(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
